### ISSUE TITLE
How should I run the streaming tensor correctly?

### ISSUE THREAD

**Issue by lwqq00** [sandialabs/GenTen#8]
Hello, I am learning about streaming tensor decompositions and very interested in "Streaming Generalised Canonical Polyadic Tensor Decompositions" published in PASC23.
However, when I try to reproduce it, I use the following command. 
```
./bin/genten --input ../data/chicago-crime-comm-filtered3.txt --streaming-solver online-cp --history-method ktensor-fro --window-method reservoir --window-size 10 --window-weight 1.0 --output-file stream_output.ktns --history-file chicago_crime_history.txt
```
But I can't observe if the streaming-solver is called successfully or not. Since this is my first encounter with a codebase as complex as genten, I have some overwhelmed.
I would like to ask if I am executing the command correctly? Also, how should I verify that streaming-solver is being used?

THANKS!

**Comment by etphipp** [comment]
Thanks for reaching out.  Unfortunately the streaming solver currently can't be run from the command-line as you discovered (I should at least add an error message stating that).  The results in that paper were created by running GenTen through the Matlab interface [here](https://github.com/sandialabs/GenTen/blob/master/matlab/Genten_Matlab_Online_GCP.cpp).  The issue is the command-line driver doesn't have an interface for reading the streaming slices, mainly because it wasn't clear to me what the utility would be in actually doing that.  If you are mainly just interested in playing around with this, would the Matlab interface work for you?  I could post some code as an example to get you up and running with it.  Alternatively, I could also probably get it up and running with the Python interface.  I could also get the command-line interface setup for it, but it might take a little time and I would have to decide on an interface for specifying how the tensor slices are brought in.

**Comment by etphipp** [comment]
I created a python interface for the streaming GCP algorithm, and created two python notebooks that demonstrate how to use it:  one for synthetic data and Gaussian loss [here](https://github.com/sandialabs/GenTen/blob/master/python/example/streaming_gcp_synthetic_gaussian.ipynb) and one using the Chicago Crime data from FROSTT with Bernoulli loss [here](https://github.com/sandialabs/GenTen/blob/master/python/example/streaming_gcp_chicago_binary.ipynb).  As you can see from the Chicago Crime example, there is a lot of preprocessing that is required for the streaming algorithm to reorder the modes, split the tensor into sub-tensors along the temporal mode, and compute a warm-start, not to mention the multiple parameter lists that are needed for the streaming solver.  It really isn't practical to include all of those preprocessing steps into the command-line driver, which is why I'm reluctant to do that.  I am hoping the python interface will be sufficient for your needs.
